# These are supported funding model platforms

github: ham2anv # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: PaulStefko # Replace with a single Patreon username
ko_fi: paulstefko # Replace with a single Ko-fi username
